export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_BY_QUERY = 'GET_PRODUCT_CATEGORIES_BY_QUERY';
export const GET_TAG_BY_ID = 'GET_TAG_BY_ID';
export const TAG_DATA_ON_PROGRESS = 'TAG_DATA_ON_PROGRESS';
export const TAG_DATA_SUBMIT_PROGRESS = 'TAG_DATA_SUBMIT_PROGRESS';
export const OPEN_TAG_SIDEBAR = 'OPEN_TAG_SIDEBAR';
export const BIND_TAG_BASIC_INFO = 'BIND_TAG_BASIC_INFO';
export const GET_TAG_DROPDOWN = 'GET_TAG_DROPDOWN';
