export const GET_PRODUCT_SUB_CATEGORIES = 'GET_PRODUCT_SUB_CATEGORIES';
export const GET_PRODUCT_SUB_CATEGORIES_BY_QUERY =
  'GET_PRODUCT_SUB_CATEGORIES_BY_QUERY';
export const GET_PRODUCT_SUB_CATEGORY_BY_ID = 'GET_PRODUCT_SUB_CATEGORY_BY_ID';
export const PRODUCT_SUB_CATEGORY_DATA_ON_PROGRESS =
  'PRODUCT_SUB_CATEGORY_DATA_ON_PROGRESS';
export const PRODUCT_SUB_CATEGORY_DATA_SUBMIT_PROGRESS =
  'PRODUCT_SUB_CATEGORY_DATA_SUBMIT_PROGRESS';
export const OPEN_PRODUCT_SUB_CATEGORY_SIDEBAR =
  'OPEN_PRODUCT_SUB_CATEGORY_SIDEBAR';
export const BIND_PRODUCT_SUB_CATEGORY_BASIC_INFO =
  'BIND_PRODUCT_SUB_CATEGORY_BASIC_INFO';
export const DROP_DOWN_PRODUCT_SUB_CATEGORY = 'DROP_DOWN_PRODUCT_SUB_CATEGORY';
