export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_QUERY = 'GET_PRODUCTS_BY_QUERY';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const PRODUCT_DATA_ON_PROGRESS = 'PRODUCT_DATA_ON_PROGRESS';
export const PRODUCT_DATA_SUBMIT_PROGRESS = 'PRODUCT_DATA_SUBMIT_PROGRESS';
export const OPEN_PRODUCT_SIDEBAR = 'OPEN_PRODUCT_SIDEBAR';
export const BIND_PRODUCT_BASIC_INFO = 'BIND_PRODUCT_BASIC_INFO';
