export const GET_ATTRIBUTES = 'GET_ATTRIBUTES';
export const GET_ATTRIBUTES_BY_QUERY = 'GET_ATTRIBUTES_BY_QUERY';
export const GET_ATTRIBUTE_BY_ID = 'GET_ATTRIBUTE_BY_ID';
export const ATTRIBUTE_DATA_ON_PROGRESS = 'ATTRIBUTE_DATA_ON_PROGRESS';
export const ATTRIBUTE_DATA_SUBMIT_PROGRESS = 'ATTRIBUTE_DATA_SUBMIT_PROGRESS';
export const OPEN_ATTRIBUTE_SIDEBAR = 'OPEN_ATTRIBUTE_SIDEBAR';
export const BIND_ATTRIBUTE_BASIC_INFO = 'BIND_ATTRIBUTE_BASIC_INFO';

export const GET_ATTRIBUTE_DROPDOWN = 'GET_ATTRIBUTE_DROPDOWN';
export const GET_ATTRIBUTE_VALUES_DROPDOWN = 'GET_ATTRIBUTE_VALUES_DROPDOWN';
