export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';
export const GET_PRODUCT_CATEGORIES_BY_QUERY =
  'GET_PRODUCT_CATEGORIES_BY_QUERY';
export const GET_PRODUCT_CATEGORY_BY_ID = 'GET_PRODUCT_CATEGORY_BY_ID';
export const PRODUCT_CATEGORY_DATA_ON_PROGRESS =
  'PRODUCT_CATEGORY_DATA_ON_PROGRESS';
export const PRODUCT_CATEGORY_DATA_SUBMIT_PROGRESS =
  'PRODUCT_CATEGORY_DATA_SUBMIT_PROGRESS';
export const OPEN_PRODUCT_CATEGORY_SIDEBAR = 'OPEN_PRODUCT_CATEGORY_SIDEBAR';
export const BIND_PRODUCT_CATEGORY_BASIC_INFO =
  'BIND_PRODUCT_CATEGORY_BASIC_INFO';
